alias: AC Window Open Notification
id: 75205dc0-69e5-5502-a80d-4895b45546dd
description: AC Windows Reminder
mode: single
trigger:
  - platform: state
    entity_id:
      - climate.home
    attribute: hvac_action
    to: cooling
    for:
      minutes: 1
condition:
  - condition: state
    entity_id: group.window_sensors
    state: "on"
action:
  - if:
      - condition: state
        entity_id: person.jena
        state: home
    then:
      - service: notify.jena_phone
        data:
          title: Batten down the hatches!
          message: >
            {{ states | selectattr('entity_id','in',
            state_attr('group.window_sensors','entity_id')) |
            selectattr('state','eq','on') | map(attribute='name') | join(', ')
            }} are open!
  - if:
      - condition: state
        entity_id: person.mike
        state: home
    then:
      - service: notify.mike_phone
        data:
          title: Batten down the hatches!
          message: >
            {{ states | selectattr('entity_id','in',
            state_attr('group.window_sensors','entity_id')) |
            selectattr('state','eq','on') | map(attribute='name') | join(', ')
            }} are open!
