alias: HACS Update Notification
id: 787c69bd-327c-48b5-8b15-3277cf0c93b0
description: Check for HACS updates at noon and send notification
mode: single

trigger:
  - platform: time
    at: "12:00:00"

condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: sensor.hacs
        state: "0"

action:
  - service: notify.mike_phone
    data:
      title: HACS Updates Available!
      message: |
        {{ states('sensor.hacs') }} HACS plugin update(s) available!
      data:
        # iOS
        url: /hacs/entry
        # Android
        clickAction: /hacs/entry
