alias: tasks/hacs_update_notification.yaml
description: Check for HACS updates at noon and send notification
id: 3771c648-8131-4ea1-876a-abcd2b50d49c
mode: single
trigger:
  - platform: time
    at: "12:00:00"
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: sensor.hacs
        state: "0"
action:
  - service: notify.mike_phone
    data:
      title: HACS Updates Available!
      message: |
        {{ states('sensor.hacs') }} HACS plugin update(s) available!
      data:
        # iOS
        url: &url /hacs/entry
        # Android
        clickAction: *url
