alias: tasks/hacs_update_notification.yaml
description: Check for HACS updates at noon and send notification
mode: single

trigger:
  - platform: time
    at: "12:00:00"

condition:
  - condition: state
    entity_id: sensor.hacs
    state: "0"
    negate: true

action:
  - service: notify.mike_phone
    data:
      title: HACS Updates Available!
      message: |
        {{ states('sensor.hacs') }} HACS plugin update(s) available!
      data:
        # iOS
        url: /hacs/entry
        # Android
        clickAction: /hacs/entry
