alias: Waste Collection Reminder
id: 75205dc0-69e5-4502-a89d-4895b45546de
description: Waste collection reminder
mode: single
trigger:
  - platform: calendar
    event: start
    offset: "-06:00:00"
    entity_id: calendar.waste_collection
condition: []
action:
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ trigger.calendar_event.summary in ["Garbage", "Garbage & Glass"] }}
        sequence:
          - service: notify.jena_phone
            data:
              title: Waste Collection Reminder
              message: |
                {{ trigger.calendar_event.summary }} pickup is tomorrow!
    default:
      - service: notify.mike_phone
        data:
          title: Waste Collection Reminder
          message: |
            {{ trigger.calendar_event.summary }} pickup is tomorrow!