alias: tasks/action_handlers/ender_actions.yaml
id: f6045fd6-c2d7-4658-bb03-e6eed6676789
description: 'Confirm action, then cancel print'
mode: parallel
trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: ENDER_CANCEL_PRINT
    id: cancel
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: POWER_OFF_ENDER
    id: power_off
condition: []
action:
  - alias: "Set up variables for the actions"
    variables:
      action_confirm: "{{ 'CONFIRM_' ~ context.id }}"
      action_deny: "{{ 'DENY_' ~ context.id }}"
  - service: notify.mike_phone
    data:
      message: "Are you sure you want to perform {{ trigger.id }} action on Ender?"
      data:
        actions:
          - action: "{{ action_confirm }}"
            title: Confirm
          - action: "{{ action_deny }}"
            title: Deny
  - alias: "Perform the action"
    choose:
      - conditions: 
          - "{{ wait.trigger.event.data.action == action_confirm }}"
          - "{{ trigger.id == 'cancel' }}"
        sequence:
          - service: button.press
            target:
              entity_id: button.ender_cancel_print
      - conditions: 
          - "{{ wait.trigger.event.data.action == action_confirm }}"
          - "{{ trigger.id == 'power_off' }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: switch.ender3
