alias: tasks/action_handlers/front_door.yaml
id: f6045fd6-c2d7-4658-bb03-e6eed8877718
description: ''
mode: single
trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: FRONT_DOOR_LOCK
    id: LOCK
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: FRONT_DOOR_UNLOCK
    id: UNLOCK
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: UNLOCK
          - condition: state
            entity_id: lock.front_door_lock
            state: locked
        sequence:
          - service: lock.unlock
            target:
              entity_id: lock.front_door_lock
      - conditions:
          - condition: trigger
            id: LOCK
          - condition: state
            entity_id: lock.front_door_lock
            state: unlocked
        sequence:
          - service: lock.lock
            target:
              entity_id: lock.front_door_lock
    default: []
