alias: tasks/action_handlers/garage_door.yaml
id: 628caa03-f695-4ab8-9e56-a5c41c582788
description: ''
mode: single
trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: GARAGE_DOOR_CLOSE
    id: CLOSE
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: GARAGE_DOOR_OPEN
    id: OPEN
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: OPEN
          - condition: device
            domain: cover
            entity_id: cover.garage_door
            type: is_closed
        sequence:
          - domain: cover
            entity_id: cover.garage_door
            type: open
      - conditions:
          - condition: trigger
            id: CLOSE
          - condition: device
            domain: cover
            entity_id: cover.garage_door
            type: is_open
        sequence:
          - domain: cover
            entity_id: cover.garage_door
            type: close
    default: []