alias: tasks/action_handlers/garage_door.yaml
id: 628caa03-f695-4ab8-9e56-a5c41c582788
description: ''
mode: single
trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: GARAGE_DOOR_CLOSE
    id: CLOSE
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: GARAGE_DOOR_OPEN
    id: OPEN
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: OPEN
          - condition: state
            entity_id: cover.gdo_door
            state: closed
        sequence:
          - service: cover.open_cover
            target:
              entity_id: cover.gdo_door
      - conditions:
          - condition: trigger
            id: CLOSE
          - condition: state
            entity_id: cover.gdo_door
            state: open
        sequence:
          - service: cover.close_cover
            target:
              entity_id: cover.gdo_door
    default: []