alias: tasks/action_handlers/scene_hue_go_selector.yaml
id: 3d087255-fa9b-475a-a5f4-a347289d8e32
description: scene triggers for hue go
mode: single
trigger:
  - platform: state
    entity_id: light.hue_go
condition: []
action:
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ trigger.to_state.state == "On" }}'
        sequence:
          - service: light.turn_on
            target:
              entity_id: light.hue_go
      - conditions:
          - condition: template
            value_template: '{{ trigger.to_state.state == "Off" }}'
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.hue_go
      - conditions:
          - condition: template
            value_template: '{{ trigger.to_state.state == "Dimmed" }}'
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: 50
            target:
              entity_id: light.hue_go
      - conditions:
          - condition: template
            value_template: '{{ trigger.to_state.state == "Night Light" }}'
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: 10
            target:
              entity_id: light.hue_go
    default: []
