alias: rooms/garage/christmas_light_timer.yaml
id: e65a23fa-63b7-4caf-bcf6-26ccc9ffabde
description: Outdoor christmas lights timer
mode: single

# Turn on lights at sunset, 45 minutes before
# Turn off lights at sunset + 6 hours
trigger:
  - platform: sun
    event: sunset
    offset: "-00:45:00"
    id: "turn_on"
  - platform: sun
    event: sunset
    offset: "+06:00:00"
    id: "turn_off"

# Only run this automation between Nov 20 and Jan 5
condition: 
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ now().month == 11 and now().day > 20 }}"
      - condition: template
        value_template: "{{ now().month == 12 }}"
      - condition: template
        value_template: "{{ now().month == 1 and now().day <= 5 }}"

# Perform the appropriate action based on the trigger id
action:
  - service: light.{{ trigger.id }}
    target:
      entity_id: light.outdoor_christmas_lights
