alias: rooms/garage/motion_light_on.yaml
id: d3e91c77-8ef1-4cc7-b110-86cd9eccdfae
description: motion detected in garage
mode: single
trigger:
  - platform: state
    entity_id:
      - binary_sensor.garage_motion_detector_occupancy
    to: "on"
condition:
  - condition: state
    entity_id: light.garage_light
    state: "off"
action:
  - service: light.turn_on
    target:
      entity_id: light.garage_light
