alias: rooms/garage/motion_light_on.yaml
id: d3e91c77-8ef1-4cc7-b110-86cd9eccdfae
description: Turn on garage light when motion is detected
mode: single

# Trigger the automation when motion is detected in the garage
trigger:
  - platform: state
    entity_id: binary_sensor.garage_motion_detector_occupancy
    to: "on"

# Only run the automation if the garage light is off
condition:
  - condition: state
    entity_id: light.garage_light
    state: "off"

# Turn on the garage light when the trigger and conditions are met
action:
  - service: light.turn_on
    target:
      entity_id: light.garage_light
