alias: rooms/garage/motion_light_on.yaml
id: d3e91c77-8ef1-4cc7-b110-86cd9eccdfae
description: motion detected in garage
mode: single
trigger:
  - type: motion
    platform: device
    entity_id: binary_sensor.garage_motion_detector_occupancy
    domain: binary_sensor
condition:
  - condition: device
    type: is_off
    entity_id: light.garage_light
    domain: light
action:
  - service: homeassistant.turn_on
    target:
      entity_id: light.garage_light