alias: rooms/garage/no_motion_light_off.yaml
id: 24602d24-0843-414d-93d8-dc6f750de31f
description: turn light off after 15 minutes
mode: single
trigger:
  - type: no_motion
    platform: device
    entity_id: binary_sensor.garage_motion_detector_occupancy
    domain: binary_sensor
    for:
      hours: 0
      minutes: 10
      seconds: 0
condition:
  - condition: device
    type: is_on
    entity_id: light.garage_light
    domain: light
action:
  - service: homeassistant.turn_off
    target:
      entity_id: light.garage_light
