alias: rooms/garage/no_motion_light_off.yaml
id: 24602d24-0843-414d-93d8-dc6f750de31f
description: turn light off after 15 minutes
mode: single
trigger:
  - platform: state
    entity_id:
      - binary_sensor.garage_motion_detector_occupancy
    to: "off"
    for:
      hours: 0
      minutes: 15
      seconds: 0
  - platform: state
    entity_id:
      - light.garage_light
    to: "on"
    for:
      hours: 0
      minutes: 15
      seconds: 0
condition:
  - condition: state
    entity_id: binary_sensor.garage_motion_detector_occupancy
    state: "off"
    for:
      hours: 0
      minutes: 10
      seconds: 0
  - condition: state
    entity_id: light.garage_light
    state: "on"
action:
  - service: homeassistant.turn_off
    target:
      entity_id: light.garage_light
