alias: rooms/garage/no_motion_light_off.yaml
id: 24602d24-0843-414d-93d8-dc6f750de31f
description: turn light off after 15 minutes
mode: single
trigger:
  - type: no_motion
    platform: device
    device_id: 3b5c0fd10dac7d134497b220b6411b9e
    entity_id: binary_sensor.garage_motion_detector_occupancy
    domain: binary_sensor
    for:
      hours: 0
      minutes: 10
      seconds: 0
condition:
  - condition: device
    type: is_on
    device_id: 2c64cb0b000b485c989b1e0c44cfdf3c
    entity_id: switch.garage_light
    domain: switch
action:
  - type: turn_off
    device_id: 2c64cb0b000b485c989b1e0c44cfdf3c
    entity_id: switch.garage_light
    domain: switch
