alias: people/jena/morning/hue_go_routine.yaml
id: 5cc08cda-5ac8-4f24-80c9-869cb75ad7d7

description: Turn Hue Go on in the morning

# The following is the trigger for this automation
# When the following condition is met, the automation will be triggered
trigger:
  # The automation is triggered 5 minutes before Jena's alarm time
  - platform: template
    value_template: >- 
      {{ now().timestamp() | timestamp_custom('%H:%M') == (state_attr('input_datetime.jena_alarm', 'timestamp') - 5*60) | timestamp_custom('%H:%M', false) }}

# The following are the conditions that must be met for the automation to be executed
# This automation will only be executed if Jena is home, it is a workday, and the current month is between September and May
condition:
  - condition: state
    entity_id: input_boolean.jena_alarm_enabled
    state: 'on'
  - condition: state
    entity_id: person.jena
    state: home
  - condition: state
    entity_id: binary_sensor.workday
    state: 'on'
  - condition: template
    value_template: '{{ now().month >= 8 or now().month <= 4 }}'

# The following are the actions that will be executed when the automation is triggered
# This automation will turn on the Hue Go light with a specified transition, brightness step, and color temperature
# It will then turn off the light 25 minutes later
mode: single
action:
  # Turn on the Hue Go light
  - service: light.turn_on
    data:
      transition: 300
      brightness_step: 200
      color_temp: 355
    target:
      entity_id: light.hue_go
  # Wait 25 minutes
  - wait_for_trigger:
      - platform: state
        entity_id:
          - light.guest_bedroom_light
        to: "on"
    timeout:
      minutes: 25
  # Turn off the Hue Go light
  - service: light.turn_off
    target:
      entity_id: light.hue_go
