alias: people/jena/morning/turn_off_lights_away.yaml
id: c3526df7-9570-4c5e-97cc-84c16f59129a
description: Turn on heated floors in the morning
mode: single
trigger:
  - platform: template
    value_template: >-
      {{ now().timestamp() | timestamp_custom('%H:%M') == (state_attr('input_datetime.jena_alarm', 'timestamp') - 1*60) | timestamp_custom('%H:%M', false) }}
condition:
  - condition: state
    entity_id: person.jena
    state: home
  - condition: state
    entity_id: binary_sensor.workday
    state: 'on'
action:
  - wait_for_trigger:
      - platform: zone
        entity_id: person.jena
        zone: zone.home
        event: leave
      - platform: state
        entity_id:
          - lock.front_door_lock
        to: unlocked
    timeout: '1800'
  - service: homeassistant.turn_off
    target:
      area_id: 
        - kitchen
        - living_room
