alias: alarm/leaving_home.yaml
id: 40587902-cef5-435e-8b42-15b2059d4b33
description: 'Arm alarm when leaving home'
trigger:
  - platform: zone
    entity_id: person.jena
    zone: zone.home
    event: leave
  - platform: zone
    entity_id: person.mike
    zone: zone.home
    event: leave
condition:
  - condition: not
    conditions:
      - condition: or
        conditions:
          - condition: zone
            entity_id: person.jena
            zone: zone.home
          - condition: zone
            entity_id: person.mike
            zone: zone.home
action:
  - service: alarm_control_panel.alarm_arm_away
    data: {}
    target:
      entity_id: alarm_control_panel.home_alarm
mode: single
