alias: alarm/notify_armed_home.yaml
id: e86d5dea-8520-46fc-8ef7-e36d8b88b4fe
description: Notify when alarm is armed in home mode

trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: armed_home

condition:
  - condition: time
    before: '23:00:00'
    after: '07:00:00'

action:
  - service: notify.all_devices
    data:
      title: "Home Alarm: Armed"
      message: |
        The alarm is armed in home mode {{ states('sensor.date_time') }}

mode: single
