alias: alarm/notify_disarmed.yaml
id: 80b25030-d09b-479b-a1b4-d397d53bb885
description: 'Notify when alarm is disarmed'
trigger:
  - platform: state
    entity_id: alarm_control_panel.home_alarm
    to: disarmed
action:
  - service: notify.notify
    data:
      title: "Home Alarm: Disarmed"
      message: The alarm is disarmed at {{ states('sensor.date_time') }}
