- id: '1658266860192'
  alias: people/jena/button.yaml
  description: ''
  use_blueprint:
    path: tradfri/button.yaml
    input:
      remote_entity: sensor.jena_button_action
      light_entity:
        entity_id:
        - light.christmas_twree
        - light.wled_livingroom_master
