- id: '1658266860192'
  alias: people/jena/button.yaml
  description: ''
  use_blueprint:
    path: tradfri/button.yaml
    input:
      remote_entity: sensor.jena_button_action
      light_entity:
        entity_id:
        - light.christmas_twree
        - light.wled_livingroom
- id: '1669188391981'
  description: ''
  trigger:
  - platform: state
    entity_id: []
  - platform: state
    entity_id:
    - lock.front_door_lock
    to: unlocked
    for:
      hours: 0
      minutes: 5
      seconds: 0
  - platform: state
    entity_id:
    - binary_sensor.garage_entry_contact
    to: 'on'
  - platform: state
    entity_id:
    - binary_sensor.garage_motion_detector_occupancy
    to: 'on'
  condition:
  - condition: state
    entity_id: light.entry_light
    state: 'off'
  - condition: state
    entity_id: lock.front_door_lock
    state: unlocked
  - condition: state
    entity_id: light.garage_light
    state: 'off'
  action:
  - wait_for_trigger:
    - platform: state
      entity_id:
      - binary_sensor.garage_motion_detector_occupancy
      to: 'on'
  - service: lock.lock
    data: {}
    target:
      entity_id: lock.front_door_lock
  mode: single
