# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  customize: !include customize.yaml

http:
  server_host: 0.0.0.0
  ip_ban_enabled: true
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.244.0.0/16

logger:
  default: error

frontend:
  themes: !include_dir_merge_named themes

recorder:

alert: !include alerts.yaml
automation ui: !include automations.yaml
script ui: !include scripts.yaml
script yaml: !include_dir_named scripts/
scene: !include scenes.yaml
light: !include lights.yaml
group: !include_dir_named groups/
input_boolean: !include_dir_merge_named input_booleans/
binary_sensor: !include_dir_list binary_sensors/
mqtt: !include mqtt.yaml

sensor:
  - platform: waste_collection_schedule
    name: next_collection
  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "date_time"
      - "date_time_utc"
      - "date_time_iso"
      - "time_date"
      - "time_utc"
  - platform: gtfs_rt
    trip_update_url: !secret gtfs_trip_update_url
    vehicle_position_url: !secret gtfs_vehicle_position_url
    departures:
      - name: Bus To Work
        route: !secret gtfs_bus_route
        stopid: !secret gtfs_to_work_bus_stopid
      - name: Bus To Home
        route: !secret gtfs_bus_route
        stopid: !secret gtfs_to_home_bus_stopid
  - platform: template
    sensors:
      tesla_est_battery_range_mi:
        friendly_name: Estimated Range (mi)
        unit_of_measurement: mi
        icon_template: mdi:gauge
        value_template: >
          {{ (states('sensor.tesla_est_battery_range_km') | float / 1.609344) | round(2) }}

      tesla_rated_battery_range_mi:
        friendly_name: Rated Range (mi)
        unit_of_measurement: mi
        icon_template: mdi:gauge
        value_template: >
          {{ (states('sensor.tesla_rated_battery_range_km') | float / 1.609344) | round(2) }}

      tesla_ideal_battery_range_mi:
        friendly_name: Ideal Range (mi)
        unit_of_measurement: mi
        icon_template: mdi:gauge
        value_template: >
          {{ (states('sensor.tesla_ideal_battery_range_km') | float / 1.609344) | round(2) }}

      tesla_odometer_mi:
        friendly_name: Odometer (mi)
        unit_of_measurement: mi
        icon_template: mdi:counter
        value_template: >
          {{ (states('sensor.tesla_odometer') | float / 1.609344) | round(2) }}

      tesla_speed_mph:
        friendly_name: Speed (MPH)
        unit_of_measurement: mph
        icon_template: mdi:speedometer
        value_template: >
          {{ (states('sensor.tesla_speed') | float / 1.609344) | round(2) }}

      tesla_elevation_ft:
        friendly_name: Elevation (ft)
        unit_of_measurement: ft
        icon_template: mdi:image-filter-hdr
        value_template: >
          {{ (states('sensor.tesla_elevation') | float * 3.2808 ) | round(2) }}

      tesla_tpms_pressure_fl_psi:
        friendly_name: Front Left Tire Pressure (psi)
        unit_of_measurement: psi
        icon_template: mdi:car-tire-alert
        value_template: >
          {{ (states('sensor.tesla_tpms_fl') | float * 14.50377) | round(2) }}

      tesla_tpms_pressure_fr_psi:
        friendly_name: Front Right Tire Pressure (psi)
        unit_of_measurement: psi
        icon_template: mdi:car-tire-alert
        value_template: >
          {{ (states('sensor.tesla_tpms_fr') | float * 14.50377) | round(2) }}

      tesla_tpms_pressure_rl_psi:
        friendly_name: Rear Left Tire Pressure (psi)
        unit_of_measurement: psi
        icon_template: mdi:car-tire-alert
        value_template: >
          {{ (states('sensor.tesla_tpms_rl') | float * 14.50377) | round(2) }}

      tesla_tpms_pressure_rr_psi:
        friendly_name: Rear Right Tire Pressure (psi)
        unit_of_measurement: psi
        icon_template: mdi:car-tire-alert
        value_template: >
          {{ (states('sensor.tesla_tpms_rr') | float * 14.50377) | round(2) }}
  - platform: template
    sensors:
      tesla_park_brake:
        friendly_name: Parking Brake
        icon_template: mdi:car-brake-parking
        value_template: >-
          {% if is_state('sensor.tesla_shift_state', 'P') %}
            ON
          {% else %}
            OFF
          {% endif %}

template:
  - sensor:
      - name: Living Room And Kitchen
        state: "{{ states('group.living_room_kitchen') }}"
        attributes:
          current_temperature: "{{ state_attr('climate.home', 'current_temperature') }}"
      - name: Master Bed And Bathroom
        state: "{{ states('group.master_bed_bathroom') }}"
        attributes:
          current_temperature: "{{ states('sensor.master_bathroom_sensor_temperature') }}"
      - name: Guest Bed And Bathroom
        state: "{{ states('group.guest_bed_bathroom') }}"
        attributes:
          current_temperature: "{{ states('sensor.guest_bathroom_sensor_temperature') }}"
      - name: Garage And Entry
        state: "{{ states('group.garage_entry') }}"
        attributes:
          current_temperature: "{{ states('sensor.garage_temperature') }}"
      - name: Home HVAC Action
        state: "{{ state_attr('climate.home', 'hvac_action') }}"

  - binary_sensor:
      - name: Is Christmas-ish time
        state: >
          {% set current = now() %}
          {{ (current.month == 11 and current.day > 18) 
            or current.month == 12 or (current.month == 1
            and current.day <= 2) }}
      - name: Indoor Temperature Falling & Heating On
        state: "{{ is_state('binary_sensor.indoor_temperature_falling', 'on') and is_state_attr('climate.home', 'hvac_action', 'heating') and (now() - states.climate.home.last_changed) > timedelta(minutes=30) }}"
      - name: Indoor Temperature Rising & Cooling On
        state: "{{ is_state('binary_sensor.indoor_temperature_rising', 'on') and is_state_attr('climate.home', 'hvac_action', 'cooling') and (now() - states.climate.home.last_changed) > timedelta(minutes=30) }}"

notify:
  - name: ALL_DEVICES
    platform: group
    services:
      - service: mobile_app_mike_phone
      - service: mobile_app_iphone_210
  - name: mike_phone
    platform: group
    services:
      - service: mobile_app_mike_phone
  - name: jena_phone
    platform: group
    services:
      - service: mobile_app_iphone_210

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/frigate-hass-card/frigate-hass-card.js
      type: module
    - url: /hacsfiles/light-entity-card/light-entity-card.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: module
    - url: /hacsfiles/lovelace-collapsable-cards/collapsable-cards.js
      type: module
    - url: /hacsfiles/lovelace-hourly-weather/hourly-weather.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/my-cards/my-cards.js
      type: module
    - url: /hacsfiles/secondaryinfo-entity-row/secondaryinfo-entity-row.js
      type: module
    - url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js
      type: module
    - url: /hacsfiles/weather-radar-card/weather-radar-card.js
      type: module
    - url: /hacsfiles/webrtc/webrtc-camera.js?
      type: module

waste_collection_schedule:
  sources:
    - name: ics
      calendar_title: Waste Collection
      args:
        url: !secret waste_collection_schedule_ics_url
      customize:
        - type: Recycling and green waste
          alias: Recycling
        - type: Garbage and green waste
          alias: Garbage
        - type: Garbage, green waste, and glass recycling
          alias: Garbage & Glass
        - type: Recycling, green waste, and glass recycling
          alias: Recycling & Glass
        - type: Recycling, glass recycling, and green waste
          alias: Recycling & Glass
        - type: Garbage, glass recycling, and green waste
          alias: Garbage & Glass

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_control_panel_code
    # Don't require the code to arm the alarm
    code_arm_required: false
    # Arm again after treiggering
    disarm_after_trigger: false
    # Delay from arming and becoming armed, eg. to leave the house
    arming_time: 120
    # Allow time to disarm the alarm before it triggers, eg. when arriving home
    delay_time: 60
    # Amount of time the alarm is triggered for
    trigger_time: 600
    disarmed:
      # Ensure the alarm can never be directly triggered when disarmed
      trigger_time: 0
    armed_home:
      arming_time: 0
    armed_night:
      arming_time: 30
