button_card_templates: !include_dir_merge_named minimalist-templates/
kiosk_mode:
  kiosk: true
views:
  - title: Alarm Panel
    path: alarm
    cards:
      - type: vertical-stack
        cards:
          - type: alarm-panel
            states:
              - arm_home
              - arm_away
            entity: alarm_control_panel.home_alarm
            card_mod:
              style: |
                ha-card { 
                  --paper-input-container-shared-input-style_-_font-size: 2.5rem;
                  --keypad-font-size: 2.5rem;
                  --mdc-typography-button-font-size: 1.5rem;
                  --mdc-button-outline-color: rgba(0, 0, 0, 0);
                  --paper-font-subhead_-_font-size: 1.5rem;
                }
                #alarmCode mdc-text-field__input {
                  font-size: 35px;
                }
                #keypad {
                  width: 30%;
                  max-width: 500px !important;
                }
                #keypad mwc-button {
                  border-radius: 5px;
                }
                mwc-button.numberkey {
                  border-color: rgba(100,100,100,.1);
                  border-width: 2px;
                  border-style: solid;
                }
                #keypad mwc-button:hover {
                  background: rgba(100,100,100,.2);
                }
                #keypad mwc-button {
                  padding: 30px !important;
                  margin: 4px;
                  width: 30%;
                  box-sizing: border-box;
                  height: 85px;
                }
                paper-input {
                    max-width: 300px !important;
                }
