alias: seasons/christmas/christmas_lights_timer.yaml
id: e65a23fa-63b7-4caf-bcf6-26ccc9ffabde
description: Christmas lights timer
mode: single

trigger:
  - platform: sun
    event: sunset
    offset: "-01:30:00"
    id: "turn_on"
  - platform: sun
    event: sunset
    offset: "+07:30:00"
    id: "turn_off"

condition: 
  - condition: state
    entity_id: binary_sensor.is_christmas_ish_time
    state: "on"

action:
  - service: light.{{ trigger.id }}
    target:
      entity_id: 
        - light.christmas_tree
        - light.outdoor_christmas_lights
        - light.sonoff31_1
        - light.wled_bookshelf
        - light.wled_livingroom
  - if:
      - condition: trigger
        id: turn_on
    then:
      - service: select.select_option
        data:
          option: Christmas
