---
# This automation simulates the use of the IKEA TRADFRI Remote control
# connected through Zigbee2MQTT.

# | Button   | Action               |
# | -------- | -------------------- |
# | Power    | Toggle the light     |
# | Dim-Up   | Increase brightness  |
# | Dim-Down | Decrease brightness  |
# | Right    | Increase temperature |
# | Left     | Decrease temperature |

blueprint:
  source_url: https://gist.github.com/niro1987/f6e84c27b304f0bf3be16a8f439e8efd

  name: Zigbee2MQTT - IKEA TRADFRI - 5 Button Remote - Warm White Lights

  description: >-
    This automation simulates the use of the IKEA TRADFRI Remote control
    connected through Zigbee2MQTT.

  domain: automation

  input:
    remote_entity:
      name: Remote Sensor Entity
      description: The sensor entity created by Zigbee2MQTT
      selector:
        entity:
          domain: sensor
    light_entity:
      name: Light
      description: The light entity to control.
      selector:
        target:
          entity:
            domain: light

mode: restart

variables:
  var_light_entities: !input light_entity

trigger:
  - platform: state
    entity_id: !input remote_entity
    to:
      - "on"
      - "off"
      - "brightness_move_up"
      - "brightness_move_down"
      - "brightness_stop"

action:
  - choose:
      # Long-Press on the power button.
      - conditions:
          - condition: template
            value_template: '{{ trigger.to_state.state == "on" }}'
        sequence:
          - service: light.turn_on
            target: !input light_entity
            data:
              brightness: 255
      - conditions:
          - condition: template
            value_template: '{{ trigger.to_state.state == "off" }}'
        sequence:
          - service: light.turn_off
            target: !input light_entity
      # Long-Press on the dim-up button.
      - conditions:
          - condition: template
            value_template: '{{ trigger.to_state.state == "brightness_move_up" }}'
        sequence:
          - repeat:
              while: []
              sequence:
                - service: light.turn_on
                  target: !input light_entity
                  data:
                    brightness_step_pct: 10
                    transition: 0.5
                - delay:
                    milliseconds: 500
      # Long-Press on the dim-down button.
      - conditions:
          - condition: template
            value_template: '{{ trigger.to_state.state == "brightness_move_down" }}'
        sequence:
          - repeat:
              while: []
              sequence:
                - service: light.turn_on
                  target: !input light_entity
                  data:
                    brightness_step_pct: -10
                    transition: 0.5
                - delay:
                    milliseconds: 500
    # Any other event will cancel the repeat loops.
    default: []
