alias: rooms/guest_bathroom/fan_off.yaml
id: 6066a602-c438-4c09-b708-11f559978e51
description: Turn fan off after a while

mode: single

trigger:
  - platform: state
    entity_id:
      - fan.guest_bathroom_fan
    to: "on"
    for:
      hours: 1

action:
  - service: fan.turn_off
    target:
      entity_id: fan.guest_bathroom_fan