alias: rooms/entry/doorbell_pressed_recently.yaml
id: 5d061c50-2f2b-4cad-8ef4-dda4fe1f0108
description: Doorbell Ring Notification

mode: restart

trigger:
  - entity_id: binary_sensor.front_door_button_pressed
    platform: state
    to: 'on'
    id: turn_on
  - entity_id: binary_sensor.front_door_button_pressed
    platform: state
    to: 'on'
    id: turn_off
    for:
      minutes: 5
  - platform: time_pattern
    minutes: "/10"
    id: turn_off

action:
  - if:
      - condition: trigger
        id: turn_off
      - condition: not
        conditions:
          - condition: state
            entity_id: input_boolean.doorbell_pressed_recently
            for:
              hours: 0
              minutes: 5
              seconds: 0
            state: "on"
    then:
        - stop: was recently pressed
  - service: input_boolean.{{ trigger.id }}
    target:
      entity_id: input_boolean.doorbell_pressed_recently
