alias: rooms/entry/garage_entry_door_opened_entering.yaml
id: 524a1d6f-9419-425f-b674-89985bbab8a5
description: Automation triggered if entering entry from garage
mode: single

# Trigger the automation when the garage entry door is opened
# and the garage motion detector senses movement
trigger:
  - platform: state
    entity_id:
      - binary_sensor.garage_entry_contact
    to: "on"
    for:
      minutes: 5
  - platform: state
    entity_id: binary_sensor.garage_motion_detector_occupancy
    to: "on"

# Only run this automation if it is between 45 minutes before sunset
# and sunset
condition:
  - condition: sun
    after: sunset
    after_offset: "-00:45:00"

# Only run this automation if the entry stairs light is off
  - condition: state
    entity_id: light.entry_stairs_light
    state: "off"

# Turn on the entry stairs light
action:
  - service: light.turn_on
    target:
      entity_id: light.entry_stairs_light
