alias: rooms/entry/garage_entry_door_opened_entering.yaml
id: 524a1d6f-9419-425f-b674-89985bbab8a5
description: Automation triggered if entering entry from garage
mode: single
trigger:
  - platform: state
    entity_id:
      - binary_sensor.garage_entry_contact
    to: "on"
condition:
  - condition: state
    entity_id: binary_sensor.garage_motion_detector_occupancy
    state: "on"
  - condition: sun
    before: sunset
    after: sunset
    after_offset: '-00:45:00'
  - condition: state
    entity_id: light.entry_stairs_light
    state: "off"
action:
  - service: light.turn_on
    target:
      entity_id: light.entry_stairs_light
