alias: rooms/entry/outside_light_timer.yaml
id: e65a23fa-63b7-4caf-bcf6-26ccc9ffabbe
description: Door light timer
mode: single

# Turn on light at sunset + 20 minutes
trigger:
  - platform: sun
    event: sunset
    offset: "+00:20:00"
    id: "turn_on"
  - platform: time
    at: "20:30:00"
    id: "turn_off"
  - platform: sun
    event: sunrise
    offset: 0
    id: "turn_off"

condition:
  # Disable entry light cause christmas lights on
  - condition: state
    entity_id: binary_sensor.is_christmas_ish_time
    state: "off"

# Turn on or off the entry light based on the trigger ID
action:
  - service: light.{{ trigger.id }}
    target:
      entity_id: light.entry_light
