alias: tasks/tesla/location.yaml
id: 6d9fff5d-4dcb-4770-bfd8-3b8b527ef555
initial_state: on
trigger:
  - platform: mqtt
    topic: teslamate/cars/1/latitude
  - platform: mqtt
    topic: teslamate/cars/1/longitude
action:
  - service: device_tracker.see
    data_template:
      dev_id: tesla_location
      gps:
        [
          "{{ states.sensor.tesla_latitude.state }}",
          "{{ states.sensor.tesla_longitude.state }}",
        ]
