alias: people/coming_home.yaml
id: 0a465eb3-3489-4354-aff3-b73f1c210b4f
description: "Coming home automation"
mode: single
trigger:
  - platform: zone
    entity_id: person.jena
    zone: zone.home
    event: enter
    id: mike
  - platform: zone
    entity_id: person.mike
    zone: zone.home
    event: enter
    id: jena
condition:
  - alias: "Guest Mode Off"
    condition: state
    entity_id: input_boolean.guest_mode
    state: "off"
  # Sun is set/setting soon
  - condition: sun
    after: sunset
    after_offset: "-00:45:00"
action:
  - wait_for_trigger:
      - platform: zone
        entity_id: person.mike
        zone: zone.home
        event: enter
      - platform: zone
        entity_id: person.jena
        zone: zone.home
        event: enter
    timeout: "300"
    continue_on_timeout: false
  - service: homeassistant.turn_on
    target:
      entity_id: light.entry_stairs_light
  - delay:
      hours: 0
      minutes: 0
      seconds: 15
      milliseconds: 0
  - service: homeassistant.turn_on
    target:
      area_id: kitchen
