alias: people/coming_home.yaml
id: 0a465eb3-3489-4354-aff3-b73f1c210b4f
description: Coming home automation
mode: single

# Triggers when Jena or Mike enters the home zone
trigger:
  - platform: zone
    entity_id: person.jena
    zone: zone.home
    event: enter
  - platform: zone
    entity_id: person.mike
    zone: zone.home
    event: enter

# Only run this automation if its 2 hours before sunset, or 2 hours after sunrise
condition:
  - condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-02:00:00"
      - condition: sun
        before: sunrise
        before_offset: "02:00:00"

# Wait for both Jena and Mike to come home, then turn on the entry stairs light and kitchen lights
action:
  - wait_for_trigger:
      - platform: state
        entity_id:
          - lock.front_door_lock
        to: unlocked
  - service: light.turn_on
    target:
      entity_id:
        - light.entry_stairs_light
        - light.kitchen_light
