alias: rooms/living_room/camera_record_armed.yaml
id: 6c744410-869e-492b-86a6-7dc9e2213e37
description: Living Room 
mode: single
trigger:
  - platform: state
    entity_id:
      - alarm_control_panel.home_alarm
    to: armed_night
    id: turn_on
  - platform: state
    entity_id:
      - alarm_control_panel.home_alarm
    to: armed_away
    id: turn_on
  - platform: state
    entity_id:
      - alarm_control_panel.home_alarm
    to: disarmed
    id: turn_off
action:
  - service: homeassistant.{{ trigger.id }}
    target:
      entity_id:
        - switch.living_room_detect
        - switch.living_room_motion
        - switch.living_room_recordings
        - switch.living_room_snapshots