alias: rooms/living_room/christmas_light_timer.yaml
id: e65a23fa-63c7-4daf-bef6-2bccc911abde
description: Christmas Tree lights timer
mode: single

# Turn on lights at sunset, 45 minutes before
# Turn off lights at sunset + 6 hours
trigger:
  - platform: sun
    event: sunset
    offset: "-01:30:00"
    id: "turn_on"
  - platform: sun
    event: sunset
    offset: "+06:00:00"
    id: "turn_off"

# Only run this automation between Nov 20 and Jan 5
condition: 
  - condition: state
    entity_id: binary_sensor.is_christmas_ish_time
    state: "on"

# Perform the appropriate action based on the trigger id
action:
  - service: light.{{ trigger.id }}
    target:
      entity_id: light.outdoor_christmas_lights
