alias: rooms/living_room/heat_on.yaml
id: 6fa2a044-c22a-43b2-96aa-66f804e2bb69
description: Turn on heat in the morning
mode: single
trigger:
  - platform: template
    value_template: >-
      {{ now().timestamp() | timestamp_custom('%H:%M') == (state_attr('input_datetime.jena_alarm', 'timestamp') - 30*60) | timestamp_custom('%H:%M', false) }}
    id: jena
  - platform: template
    value_template: >-
      {{now().strftime('%a %h %d %H:%M %Z %Y') == (((state_attr('sensor.mike_phone_next_alarm', 'Time in Milliseconds') | int / 1000) - 30*60 ) | timestamp_custom('%a %h %d %H:%M %Z %Y'))}}
    id: mike
condition:
- condition: and
  conditions:
    - alias: Cold Outside
      condition: template
      value_template: >-
        "{{ state_attr('weather.home', 'temperature') | float < 5 }}"
    - alias: (Mike Home & Mike Trigger) OR (Jena Home & Jena Trigger & WorkDay)
      condition: or
      conditions:
        - condition: and
          conditions:
            - condition: state
              entity_id: person.mike
              state: home
            - condition: trigger
              id: mike
        - condition: and
          conditions:
            - condition: state
              entity_id: person.jena
              state: home
            - condition: state
              entity_id: binary_sensor.workday
              state: "on"
            - condition: trigger
              id: jena
            - condition: state
              entity_id: input_boolean.jena_alarm_enabled
              state: 'on'

action:
  - service: climate.set_temperature
    data:
      temperature: 22
    target:
      entity_id: climate.nest_thermostat
