alias: rooms/living_room/theatre_mode_reset.yaml
id: 75205dc0-69e5-4502-a89e-4895c455467b
mode: single
trigger:
  - platform: time
    at: "03:00:00"
action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.theatre_mode
