- platform: workday
  name: workday
  country: !secret country
  province: !secret province
- platform: workday
  name: workday_tomorrow
  days_offset: 1
  country: !secret country
  province: !secret province
