alias: rooms/master_bedroom/fan_off.yaml
id: 941cbb7c-d4e8-47ed-b6e8-2ddc065073e4
description: Turn fan off after a while

mode: single

trigger:
  - platform: state
    entity_id:
      - fan.master_bathroom_fan
    to: "on"
    for:
      hours: 1

action:
  - service: fan.turn_off
    target:
      entity_id: fan.master_bathroom_fan