alias: rooms/master_bathroom/fan_humidity_high.yaml
id: 6066a602-c438-4c10-b708-11f559978e60
description: Bathroom Humidity High
mode: single

variables:
  entity_id: &entity_id sensor.master_bathroom_sensor_humidity
  fan_entity_id: fan.master_bathroom_fan
  above_threshold: &above_threshold 60
  below_threshold: &below_threshold 50

trigger:
  - platform: numeric_state
    entity_id: *entity_id
    above: *above_threshold
    id: turn_on
  - platform: numeric_state
    entity_id: *entity_id
    below: *below_threshold
    for:
      minutes: 10
    id: turn_off

action:
  - service: fan.{{ trigger.id }}
    target:
      entity_id: "{{ fan_entity_id }}"
