alias: rooms/master_bathroom/heated_floors_on.yaml
id: 6fa2a044-c22a-43b2-9617-66f804e2ff69
description: Turn on heated floors in the morning
mode: single
trigger:
  - platform: template
    value_template: >-
      {{ now().timestamp() | timestamp_custom('%H:%M') == (state_attr('input_datetime.jena_alarm', 'timestamp') - 60*60) | timestamp_custom('%H:%M', false) }}
    id: jena
  - platform: template
    value_template: >-
      {{now().strftime('%a %h %d %H:%M %Z %Y') == (((state_attr('sensor.mike_phone_next_alarm', 'Time in Milliseconds') | int / 1000) - 60*60 ) | timestamp_custom('%a %h %d %H:%M %Z %Y'))}}
    id: mike
  - platform: time
    at: '07:30:00'
    id: weekend
condition:
- condition: or
  conditions:
    - condition: and
      conditions:
        - alias: "Mike is home"
          condition: state
          entity_id: person.mike
          state: "home"
        - condition: trigger
          id: mike
    - condition: and
      conditions:
        - alias: "Jena is Home"
          condition: state
          entity_id: person.jena
          state: "home"
        - alias: "Workday"
          condition: state
          entity_id: binary_sensor.workday
          state: "on"
        - condition: trigger
          id: jena
        - condition: template
          value_template: '{{ now().month >= 10 or now().month <= 4 }}'
    - condition: and
      conditions:
        - condition: trigger
          id: weekend
        - condition: or
          conditions:
          - alias: "Jena is Home"
            condition: state
            entity_id: person.jena
            state: "home"
          - alias: "Mike is Home"
            condition: state
            entity_id: person.mike
            state: "home"
        - alias: "Not a workday"
          condition: state
          entity_id: binary_sensor.workday
          state: "off"

action:
  - service: climate.set_temperature
    data:
      temperature: 27
    target:
      entity_id: climate.master_bathroom_heated_floors
  - device_id: bf5497507c63aaf34849200d9360e759
    domain: climate
    entity_id: climate.master_bathroom_heated_floors
    type: set_hvac_mode
    hvac_mode: heat
