alias: rooms/master_bathroom/heated_floors_sync_time.yaml
id: 6fa2a044-c22a-43b2-9617-66f804e2ff70
description: "Periodically sync the time on the thermostat"
mode: single

trigger:
  - platform: time
    at: "00:00:00"

condition: []

action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/Master Bathroom Heated Floors/set
      payload: '{"thermostat_time":""}'
