alias: rooms/master_bathroom/heated_floors_off.yaml
id: e152caab-f6a2-411f-b254-1d26118e6532
description: Turn heated floors off after a while
mode: single
trigger:
  - platform: state
    entity_id: 
      - climate.master_bathroom_heated_floors
    to: heat
    for:
      hours: 2
      minutes: 0
      seconds: 0
condition: []
action:
  - service: climate.turn_off
    target:
      entity_id: climate.master_bathroom_heated_floors
