alias: rooms/master_bathroom/heated_floors_off.yaml
id: e152caab-f6a2-411f-b254-1d26118e6532
description: Turn heated floors off after a while
mode: single
trigger:
  - platform: state
    entity_id: climate.master_bathroom_heated_floors
    to: heat
    for:
      hours: 2
      minutes: 0
      seconds: 0
  - type: no_motion
    platform: device
    device_id: 8dee1b01f45a35760585a0fde943de25
    entity_id: binary_sensor.master_bathroom_motion_detector_occupancy
    domain: binary_sensor
    for:
      hours: 0
      minutes: 20
      seconds: 0
condition: []
action:
  - device_id: bf5497507c63aaf34849200d9360e759
    domain: climate
    entity_id: climate.master_bathroom_heated_floors
    type: set_hvac_mode
    hvac_mode: 'off'
