alias: people/mike/morning/lights_on.yaml
id: 6204876b-18e5-4bc2-b6ee-8b8f54d97829
description: Turn on heated floors in the morning
mode: single
trigger:
  - platform: template
    value_template: >-
      {{now().strftime('%a %h %d %H:%M %Z %Y') == (((state_attr('sensor.mike_phone_next_alarm', 'Time in Milliseconds') | int / 1000) - 1*60 ) | timestamp_custom('%a %h %d %H:%M %Z %Y'))}}
condition:
  - condition: state
    entity_id: person.mike
    state: home
action:
  - wait_for_trigger:
      - platform: state
        entity_id:
          - binary_sensor.master_bathroom_motion_detector_occupancy
        to: "on"
    timeout: '1800'
    continue_on_timeout: false
  - service: homeassistant.turn_on
    target:
      area_id: master_bathroom
  - delay:
      hours: 0
      minutes: 20
      seconds: 0
      milliseconds: 0
  - service: homeassistant.turn_on
    target:
      entity_id: light.master_bedroom_light
  - service: homeassistant.turn_on
    target:
      area_id: hallway
  - wait_for_trigger:
      - platform: state
        entity_id:
          - light.master_bedroom_light
        to: "on"
    timeout: '600'
    continue_on_timeout: false
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: light.turn_on
    data:
      brightness_pct: 100
    target:
      area_id: living_room
  - service: homeassistant.turn_on
    target:
      area_id: kitchen
  - service: homeassistant.turn_off
    target:
      area_id: hallway
