alias: rooms/patio/outside_light_timer.yaml
id: 5c104d0a-ab51-4db9-8f46-50a701202c98
description: Door light timer
mode: single
trigger:
  - platform: state
    entity_id:
      - binary_sensor.patio_door_contact
    to: "off"
    for:
      hours: 1
      minutes: 0
      seconds: 0
condition:
  - condition: state
    entity_id: 
      - light.patio_lights
    state: "on"
action:
  - service: light.turn_off
    target:
      area_id: patio
