alias: rooms/patio/outside_light_timer.yaml
id: 5c104d0a-ab51-4db9-8f46-50a701202c98
description: Door light timer
mode: single
trigger:
  - type: not_opened
    platform: device
    entity_id: binary_sensor.patio_door_contact
    domain: binary_sensor
    for:
      hours: 1
      minutes: 0
      seconds: 0
condition:
  - condition: device
    type: is_on
    entity_id: light.patio_lights
    domain: light
action:
  - service: homeassistant.turn_off
    target:
      area_id: patio
