alias: rooms/patio/patio_door_opened_lights_on.yaml
id: 5004bc7f-7321-47f9-a883-e2346651a5bb
description: Patio door opened, turn on light
mode: single
trigger:
  - type: opened
    platform: device
    entity_id: binary_sensor.patio_door_contact
    domain: binary_sensor
condition:
  - condition: device
    type: is_off
    entity_id: light.patio_lights
    domain: light
  - condition: sun
    after: sunset
    after_offset: '-00:45:00'
action:
  - service: homeassistant.turn_on
    target:
      area_id: patio
