alias: rooms/office/magic_cube.yaml
id: 450b0c3f-91fd-461a-941c-449b413ebf21
description: 'Magic cube device triggers'
mode: single
trigger:
  - platform: device
    domain: mqtt
    device_id: 3088aa3c53d1adfd6d26715d45d7b002
    type: action
    subtype: shake
    discovery_id: 0x00158d0007e21f84 action_shake
    id: shake
  - platform: device
    domain: mqtt
    device_id: 3088aa3c53d1adfd6d26715d45d7b002
    type: action
    subtype: flip90
    discovery_id: 0x00158d0007e21f84 action_flip90
    id: flip
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: shake
        sequence:
          - type: toggle
            device_id: 81cfed92a781040d45804ac0c25bec36
            entity_id: switch.office_light
            domain: switch
      - conditions:
          - condition: trigger
            id: flip
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: '{{ state_attr(''cover.desk'', ''current_position'') <= 30 }}'
                sequence:
                  - service: cover.set_cover_position
                    data:
                      position: 100
                    target:
                      entity_id: cover.desk
            default:
              - service: cover.set_cover_position
                data:
                  position: 26
                target:
                  entity_id: cover.desk
    default: []
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
