alias: rooms/office/motion_light_on.yaml
id: a0f35bf5-ddb8-4ce7-b784-532141c39312
description: Turn light on when motion detected
mode: single
trigger:
  - platform: state
    entity_id: binary_sensor.entry_motion_detector_occupancy
    to: 'on'
condition:
  - condition: state
    entity_id: light.office_lights
    state: "off"
  - condition: time
    before: '21:00:00'
    after: '06:00:00'
action:
  - service: homeassistant.turn_on
    target:
      area_id: office
