alias: rooms/powder_room/fan_timer.yaml
id: 6066a602-c438-4c09-b708-11f559978e5a
description: Fan Timer Automations

mode: restart
trigger_variables:
  entity_id: &entity_id fan.powder_room_fan

variables:
  entity_id: *entity_id
  on_color: 80
  on_intensity: 40
  off_color: 160
  off_intensity: 15
  duration:
    minutes: 30
  step_transition_color: 0
  step_transition_effect: fast_blink
  step_transition_duration: 15
  step_transition_level: 100
  step_transition_last_only: true
  debug: false

trigger:
  - platform: template
    value_template: "{{ is_state(entity_id, 'on') }}"
    id: "on"
  - platform: template
    value_template: "{{ is_state(entity_id, 'off') }}"
    id: "off"

action:
  - choose:
      - conditions:
          - condition: trigger
            id: "on"
        sequence:
          - service: script.inovelli_falling_led
            data:
              entity_id: "{{ entity_id }}"
              on_color: "{{ on_color }}"
              on_intensity: "{{ on_intensity }}"
              off_color: "{{ off_color }}"
              off_intensity: "{{ off_intensity }}"
              duration: "{{ duration }}"
              step_transition_color: "{{ step_transition_color }}"
              step_transition_effect: "{{ step_transition_effect }}"
              step_transition_duration: "{{ step_transition_duration }}"
              step_transition_level: "{{ step_transition_level }}"
              step_transition_last_only: "{{ step_transition_last_only }}"
              debug: "{{ debug }}"
          - service: homeassistant.turn_off
            target:
              entity_id: "{{ entity_id }}"

      - conditions:
          - condition: trigger
            id: "off"
        sequence:
          - alias: Level Set All LEDs
            service: script.turn_on
            target:
              entity_id: script.inovelli_level_set
            data:
              variables:
                entity_id: "{{ entity_id }}"
                on_color: "{{ on_color }}"
                on_intensity: "{{ on_intensity }}"
                off_color: "{{ off_color }}"
                off_intensity: "{{ off_intensity }}"
                debug: "{{ debug }}"
