alias: rooms/powder_room/fan_timer.yaml
id: 6066a602-c438-4c09-b708-11f559978e5a
description: Fan Timer Automations

mode: restart
trigger_variables:
  entity_id: &entity_id fan.powder_room_fan

variables:
  entity_id: *entity_id
  on_color: 80
  on_intensity: 100
  off_color: 160
  off_intensity: 25
  total_leds: 7
  duration:
    minutes: 30

trigger:
  - platform: template
    value_template: "{{ is_state(entity_id, 'on') }}"
    id: "on"
  - platform: template
    value_template: "{{ is_state(entity_id, 'off') }}"
    id: "off"

action:
  - choose:
      - conditions:
          - condition: trigger
            id: "on"
        sequence:
          - service: script.inovelli_falling_led
            data:
              entity_id: "{{ entity_id }}"
              on_color: "{{ on_color }}"
              on_intensity: "{{ on_intensity }}"
              off_color: "{{ off_color }}"
              off_intensity: "{{ off_intensity }}"
              total_leds: "{{ total_leds }}"
              duration: "{{ duration }}"
          - service: homeassistant.turn_off
            target:
              entity_id: "{{ entity_id }}"

      - conditions:
          - condition: trigger
            id: "off"
        sequence:
          - alias: Level Set All LEDs
            service: script.turn_on
            target:
              entity_id: script.inovelli_level_set
            data:
              variables:
                entity_id: "{{ entity_id }}"
                on_color: "{{ on_color }}"
                on_intensity: "{{ on_intensity }}"
                off_color: "{{ off_color }}"
                off_intensity: "{{ off_intensity }}"
                total_leds: "{{ total_leds }}"
